name: Collector
on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 */1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.3'
    - run: go version

    - name: Build and run Golang file
      run: |
          go build -o myapp
          ./myapp -sort
    
    - name: Commit Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add ./vmess_kuyshare.txt
        git add ./trojan_kuyshare.txt
        git add ./vless_kuyshare.txt
        git add ./ss_kuyshare.txt
        git add ./mixed_kuyshare.txt
        git checkout main
        git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Collected"
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
